name: Test
permissions: read-all

on:
  pull_request_target:
    branches:
      - main

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: yarn install --frozen-lockfile
      - run: yarn lint:check
